on: [push, pull_request]

name: CodSpeed

jobs:
    benchmarks:
        name: Run benchmarks
        runs-on: ubuntu-latest
        env:
            RUSTFLAGS: '-Ctarget-cpu=native'
        steps:
            - uses: actions/checkout@v4

            - name: Setup rust toolchain, cache and cargo-codspeed binary
              uses: moonrepo/setup-rust@v1
              with:
                  channel: nightly
                  cache-target: release
                  bins: cargo-codspeed

            - name: Build the benchmark target(s)
              run: cargo codspeed build

            - name: Run the benchmarks
              uses: CodSpeedHQ/action@v3
              with:
                  run: cargo codspeed run
                  token: ${{ secrets.CODSPEED }}

            - name: Build the benchmark target(s)
              run: cargo codspeed build --features nightly

            - name: Run the benchmarks
              uses: CodSpeedHQ/action@v3
              with:
                  run: cargo codspeed run
                  token: ${{ secrets.CODSPEED }}
